-- Add 100 new puzzles to existing database
INSERT INTO Puzzles (category, url) VALUES 
-- Capture the Defender puzzles (20)
('Capture the Defender', 'https://lichess.org/training/wfYN9'),
('Capture the Defender', 'https://lichess.org/training/JiJWH'),
('Capture the Defender', 'https://lichess.org/training/2EDYv'),
('Capture the Defender', 'https://lichess.org/training/Bwb9A'),
('Capture the Defender', 'https://lichess.org/training/viNGa'),
('Capture the Defender', 'https://lichess.org/training/5ruYN'),
('Capture the Defender', 'https://lichess.org/training/nwyNW'),
('Capture the Defender', 'https://lichess.org/training/9b50z'),
('Capture the Defender', 'https://lichess.org/training/EOm3h'),
('Capture the Defender', 'https://lichess.org/training/eDKDO'),
('Capture the Defender', 'https://lichess.org/training/9b1Fh'),
('Capture the Defender', 'https://lichess.org/training/91KOA'),
('Capture the Defender', 'https://lichess.org/training/6RkGG'),
('Capture the Defender', 'https://lichess.org/training/uV99X'),
('Capture the Defender', 'https://lichess.org/training/ivylb'),
('Capture the Defender', 'https://lichess.org/training/gCZkS'),
('Capture the Defender', 'https://lichess.org/training/v1sfd'),
('Capture the Defender', 'https://lichess.org/training/XgcaJ'),
('Capture the Defender', 'https://lichess.org/training/cCr8O'),
('Capture the Defender', 'https://lichess.org/training/7H86l'),

-- Defensive Move puzzles (20)
('Defensive Move', 'https://lichess.org/training/p6y9q'),
('Defensive Move', 'https://lichess.org/training/kEbMz'),
('Defensive Move', 'https://lichess.org/training/d2nnz'),
('Defensive Move', 'https://lichess.org/training/Wnb2J'),
('Defensive Move', 'https://lichess.org/training/5NxH1'),
('Defensive Move', 'https://lichess.org/training/sUPER'),
('Defensive Move', 'https://lichess.org/training/6ttPm'),
('Defensive Move', 'https://lichess.org/training/ReuXj'),
('Defensive Move', 'https://lichess.org/training/6DY83'),
('Defensive Move', 'https://lichess.org/training/Fblnc'),
('Defensive Move', 'https://lichess.org/training/xhwip'),
('Defensive Move', 'https://lichess.org/training/ApdlK'),
('Defensive Move', 'https://lichess.org/training/IgGRe'),
('Defensive Move', 'https://lichess.org/training/LQBXE'),
('Defensive Move', 'https://lichess.org/training/bFJRD'),
('Defensive Move', 'https://lichess.org/training/Dto5A'),
('Defensive Move', 'https://lichess.org/training/aJqqk'),
('Defensive Move', 'https://lichess.org/training/r0m8Q'),
('Defensive Move', 'https://lichess.org/training/2B8FJ'),
('Defensive Move', 'https://lichess.org/training/SDSIa'),

-- Kingside Attack puzzles (20)
('Kingside Attack', 'https://lichess.org/training/n0j9V'),
('Kingside Attack', 'https://lichess.org/training/VkxFM'),
('Kingside Attack', 'https://lichess.org/training/P5Qiu'),
('Kingside Attack', 'https://lichess.org/training/3P4fd'),
('Kingside Attack', 'https://lichess.org/training/liqnP'),
('Kingside Attack', 'https://lichess.org/training/o1R5n'),
('Kingside Attack', 'https://lichess.org/training/fs7J5'),
('Kingside Attack', 'https://lichess.org/training/qlOBq'),
('Kingside Attack', 'https://lichess.org/training/TtBdT'),
('Kingside Attack', 'https://lichess.org/training/WvSit'),
('Kingside Attack', 'https://lichess.org/training/zRDs3'),
('Kingside Attack', 'https://lichess.org/training/uF09X'),
('Kingside Attack', 'https://lichess.org/training/Dor4r'),
('Kingside Attack', 'https://lichess.org/training/ONRFb'),
('Kingside Attack', 'https://lichess.org/training/dCAYy'),
('Kingside Attack', 'https://lichess.org/training/W9sJF'),
('Kingside Attack', 'https://lichess.org/training/880ue'),
('Kingside Attack', 'https://lichess.org/training/kYGDB'),
('Kingside Attack', 'https://lichess.org/training/X884n'),
('Kingside Attack', 'https://lichess.org/training/a3r7r'),

-- Queenside Attack puzzles (20)
('Queenside Attack', 'https://lichess.org/training/NhpzB'),
('Queenside Attack', 'https://lichess.org/training/emrTg'),
('Queenside Attack', 'https://lichess.org/training/oKzDv'),
('Queenside Attack', 'https://lichess.org/training/hd0Iv'),
('Queenside Attack', 'https://lichess.org/training/aVxkG'),
('Queenside Attack', 'https://lichess.org/training/dApYO'),
('Queenside Attack', 'https://lichess.org/training/7QCBc'),
('Queenside Attack', 'https://lichess.org/training/EBJ2U'),
('Queenside Attack', 'https://lichess.org/training/vfZUu'),
('Queenside Attack', 'https://lichess.org/training/GLQWh'),
('Queenside Attack', 'https://lichess.org/training/P6qLm'),
('Queenside Attack', 'https://lichess.org/training/hwz62'),
('Queenside Attack', 'https://lichess.org/training/u5bns'),
('Queenside Attack', 'https://lichess.org/training/Xv1PQ'),
('Queenside Attack', 'https://lichess.org/training/esDsM'),
('Queenside Attack', 'https://lichess.org/training/KKQO8'),
('Queenside Attack', 'https://lichess.org/training/B9wIi'),
('Queenside Attack', 'https://lichess.org/training/1fAO5'),
('Queenside Attack', 'https://lichess.org/training/EwryZ'),
('Queenside Attack', 'https://lichess.org/training/u1BSr'),

-- Crushing puzzles (20)
('Crushing', 'https://lichess.org/training/cqhNl'),
('Crushing', 'https://lichess.org/training/oQ55V'),
('Crushing', 'https://lichess.org/training/ladvi'),
('Crushing', 'https://lichess.org/training/FifJc'),
('Crushing', 'https://lichess.org/training/XqLNi'),
('Crushing', 'https://lichess.org/training/FCFWp'),
('Crushing', 'https://lichess.org/training/ATMDW'),
('Crushing', 'https://lichess.org/training/fvC4C'),
('Crushing', 'https://lichess.org/training/e5D11'),
('Crushing', 'https://lichess.org/training/eBm4u'),
('Crushing', 'https://lichess.org/training/zqiKI'),
('Crushing', 'https://lichess.org/training/BHOCh'),
('Crushing', 'https://lichess.org/training/OzKaK'),
('Crushing', 'https://lichess.org/training/kajsr'),
('Crushing', 'https://lichess.org/training/52tR5'),
('Crushing', 'https://lichess.org/training/47ooA'),
('Crushing', 'https://lichess.org/training/GnODg'),
('Crushing', 'https://lichess.org/training/Feq5e'),
('Crushing', 'https://lichess.org/training/ht2J5'),
('Crushing', 'https://lichess.org/training/6JZ8O');