name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Adjust this to match your Go version
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: |
        go test -v ./...
        go test -coverprofile=coverage.out ./...

  docker:
    name: Build and Push Docker Image
    needs: test  # Only runs if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main branch

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/chesswoodpecker:latest
          ${{ secrets.DOCKER_USERNAME }}/chesswoodpecker:${{ github.sha }}